### ISSUE TITLE
Is it possible to create common of common bundles

### ISSUE THREAD

**Issue by tufandevrim** [zoubin/common-bundle#2]
In your example, lodash/index.js is included in both common-red-and-green.js and common-hello-and-hi.js. Is it possible that striping lodash/index.js from both files and create into common of all bundles?

Thanks,
Devrim

**Comment by zoubin** [comment]
@tufandevrim Right now common-bundle does not support that.
It seems an interesting idea, and I think it is possible.
Would you show more cases where this feature could be useful?

**Comment by tufandevrim** [comment]
I have a use case may related to this:
- multiple entry point to my app=> /a.js and /b.js
- both have common functions need to be in common.js
- I also have a js (extra.js) file will be defer loaded and may use some of the function in common.js. This extra.js should not include functions already loaded by common.js

Is it possible stripping out functions from a bundle by checking another bundle?

Thanks,
Devrim

**Comment by zoubin** [comment]
If /a.js, /b.js and extra.js are passed to browserify as input, and common.js is configured to contain common modules of the three, it should already work as you expect.

I guess there are a lot of modules shared by /a.js and /b.js, but less shared by all the three,
so you want to create common.js from just the former two?

I think common-bundle could expose some api to make a bundle depend upon another, which should strip modules from the dependant that appear in both bundles.
Do you think that would do what you want?

F.Y.I
[`b.exclude`](https://github.com/substack/browserify-handbook#excluding) seems to do some similar work. Maybe you could check it.

**Comment by tufandevrim** [comment]
> I think common-bundle could expose some api to make a bundle depend upon another, which should strip modules from the dependant that appear in both bundles.
> Do you think that would do what you want?

That exactly what I want. I want this extra.js module depends on an existing common.js bundle. Also I should be able to configure extra.js not only depends on common.js but also a.js bundle. In other words, I want to strip functions in extra.js if those already exist in  common.js and a.js bundles

Thanks,
Devrim

**Comment by zoubin** [comment]
@tufandevrim 

> Is it possible stripping out functions from a bundle by checking another bundle?

You can do that from v0.4.0.
Check the [docs](https://github.com/reducejs/common-bundle#arrayisarrayoptionscommon--true).

Let me know if things go wrong.
Thank you for this issue!
It really helps enhancing this tool.

**Comment by tufandevrim** [comment]
Hi @zoubin 
I tried the latest version of common-bundle but it is failing due to es6 style coding. My node version is v0.12.9. I tried the run the code with --harmony flag as well but it keeps failing:

`
class Groups extends Transform {
^^^^^
SyntaxError: Unexpected reserved word
`

**Comment by tufandevrim** [comment]
Node 4 is a must to use this plug-in?

**Comment by zoubin** [comment]
Hi @tufandevrim 
I have checked the repository.
There are codes using arrow functions, class, let, Object.assign, etc.
But I think they are just syntax sugar.

So I did some code refactor, and now the latest release v0.4.2 is happy with node 0.12.x.

**Comment by tufandevrim** [comment]
Thanks it works! Please update the examples as well. map example pages should include red and green.
